version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - SQS_URL=${SQS_URL}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    networks:
      - queueNetwork
    depends_on:
      - queue
    ports:
      - ${HTTP_PORT}:3000
  ## QUEUE LOCAL (SQS INTERFACE) ##
  queue:
    image: softwaremill/elasticmq-native
    volumes:
      - ./queue.conf:/opt/elasticmq.conf
    networks:
      - queueNetwork
    ports:
      - 9324:9324
      - 9325:9325
  ### WORKER ###
  worker:
    image: queue-structure-worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - queue
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - SQS_URL=${SQS_URL}
      - QUEUE_NAME=queue01
    networks:
      - queueNetwork
  ## WORKER QUEUE02 ##
  # worker2:
  #   image: queue-structure-worker
  #   build:
  #     context: ./worker
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - queue
  #   environment:
  #     - AWS_REGION=${AWS_REGION}
  #     - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
  #     - AWS_SECRET_KEY=${AWS_SECRET_KEY}
  #     - SQS_URL=${SQS_URL}
  #     - QUEUE_NAME=queue02
  #   networks:
  #     - queueNetwork
networks:
  queueNetwork:
    driver: bridge