version: "3.8"
services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   networks:
  #     - queueNetwork
  #   ports:
  #     - 3000:3000
  ## WORKER 1 ###
  worker:
    image: queue-structure-worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends:
      - queue
    environment:
      - WORKER_ID=1
      - QUEUE=email
    networks:
      - queueNetwork
  ## WORKER 2 ###
  worker2:
    image: queue-structure-worker
    depends:
      - queue
    environment:
      - WORKER_ID=2
      - QUEUE=email
    networks:
      - queueNetwork
  ## WORKER 3 ###
  worker3:
    image: queue-structure-worker
    depends:
      - queue
    environment:
      - WORKER_ID=3
      - QUEUE=payment
    networks:
      - queueNetwork
  queue:
    image: softwaremill/elasticmq-native
    volumes:
      - ./queue.conf:/opt/elasticmq.conf
    networks:
      - queueNetwork
    ports:
      - 9324:9324
      - 9325:9325
networks:
  queueNetwork:
    driver: bridge